theme: jekyll-theme-cayman
title: Austin AI Ecosystem Initative 
description: Austin AI Ecosystem Initiative aims to establish a charter for Austin AI ecosystem participants—companies, government agencies, universities, and more—to collaboratively accelerate the development, application, and positive impacts of AI in business, government, education, and society.
